global:
  scrape_interval: 10s
rule_files:
  - /etc/prometheus/rules/alert.rules.yml
scrape_configs:
  - job_name: "mcloud-orders-app"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["orders-app:8080"]